version: '2'

services:
  samba:
    build:
      context: .
      dockerfile: Dockerfile.armhf
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /media:/media:z
    command: '-s "Music;/media/HDD500GB/Music"'

networks:
  default:
